language: ruby

os:
  - linux
  - osx

rvm:
  - 3.4 # Latest stable version
  - 3.2 # LTS
  - 3.0 # Minimum supported version

matrix:
  fast_finish: true
  allow_failures:
    - os: osx

notifications:
  email: false

install:
  - bundle install --jobs=3 --retry=3

script:
  - bundle exec gem build transmission-rss.gemspec
  - bundle exec rake
